alias bi='beet import'

# General
alias vi="nvim"
alias rip="youtube-dl --extract-audio --audio-format mp3"
alias weather="curl wttr.in" #Check the weather

#ls aliases
alias ls='ls --color=auto' # Colorize ls output
alias grep='grep --color' # same with grep
alias ll='ls -al' # Use long listing format
alias l.='ls -d .* --color=auto' # Show only hidden files

# Change ownership of files
alias take="sudo chown -R $(whoami):$(whoami)"

# APT aliases
if [ -x /usr/bin/apt ]; then
	alias aptin="sudo apt install"
	alias aptrm="sudo apt remove"
fi
